# Form implementation generated from reading ui file 'layout.ui'
# We designed the layout of the main window in QtDesigner and convert it into a python file using pyuic

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 716)
        MainWindow.setStyleSheet("background-color: rgb(221, 237, 238);\n"
"gridline-color: rgb(209, 234, 236);\n"
"font: 13pt \"Optima\" rgb(127, 127, 127);\n"
"color: rgb(19, 87, 107);")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_overview = QtWidgets.QLabel(self.centralwidget)
        self.label_overview.setGeometry(QtCore.QRect(760, 0, 71, 31))
        self.label_overview.setObjectName("label_overview")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(720, 390, 480, 281))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 691, 651))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(11)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_add.setStyleSheet("background-color: rgb(176, 216, 225);")
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_delete.setStyleSheet("background-color: rgb(176, 216, 225);")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout.addWidget(self.pushButton_delete)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_complete = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_complete.setStyleSheet("background-color: rgb(176, 216, 225);")
        self.pushButton_complete.setObjectName("pushButton_complete")
        self.horizontalLayout.addWidget(self.pushButton_complete)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_1.sizePolicy().hasHeightForWidth())
        self.tableWidget_1.setSizePolicy(sizePolicy)
        self.tableWidget_1.setStyleSheet("background-color: rgb(254, 229, 222);\n"
"selection-background-color: rgb(250, 200, 189);\n"
"")
        self.tableWidget_1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_1.setShowGrid(False)
        self.tableWidget_1.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(4)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(3, item)
        self.tableWidget_1.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_1.horizontalHeader().setHighlightSections(True)
        self.tableWidget_1.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_1.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_1.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_2.addWidget(self.tableWidget_1, 1, 0, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setStyleSheet("background-color: rgb(220, 239, 254);\n"
"selection-background-color: rgb(179, 215, 247);\n"
"")
        self.tableWidget_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setShowGrid(False)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setHighlightSections(True)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_2.addWidget(self.tableWidget_2, 3, 0, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_4.sizePolicy().hasHeightForWidth())
        self.tableWidget_4.setSizePolicy(sizePolicy)
        self.tableWidget_4.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"selection-background-color: rgb(210, 210, 211);")
        self.tableWidget_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget_4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setShowGrid(False)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.horizontalHeader().setHighlightSections(True)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_4.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_2.addWidget(self.tableWidget_4, 3, 1, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setStyleSheet("background-color: rgb(235, 241, 212);\n"
"selection-background-color: rgb(213, 225, 168);")
        self.tableWidget_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tableWidget_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_3.setShowGrid(False)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.horizontalHeader().setHighlightSections(True)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_3.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout_2.addWidget(self.tableWidget_3, 1, 1, 1, 1)
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 2, 0, 1, 1)
        self.label4 = QtWidgets.QLabel(self.layoutWidget)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 2, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(self.layoutWidget)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 0, 1, 1)
        self.label3 = QtWidgets.QLabel(self.layoutWidget)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_enddate = QtWidgets.QLabel(self.layoutWidget)
        self.label_enddate.setObjectName("label_enddate")
        self.gridLayout.addWidget(self.label_enddate, 1, 3, 1, 1)
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_end.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateTimeEdit_end.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.gridLayout.addWidget(self.dateTimeEdit_end, 1, 4, 1, 1)
        self.label_task = QtWidgets.QLabel(self.layoutWidget)
        self.label_task.setObjectName("label_task")
        self.gridLayout.addWidget(self.label_task, 0, 0, 1, 1)
        self.lineEdit_task = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_task.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_task.setObjectName("lineEdit_task")
        self.gridLayout.addWidget(self.lineEdit_task, 0, 1, 1, 1)
        self.label_priority = QtWidgets.QLabel(self.layoutWidget)
        self.label_priority.setObjectName("label_priority")
        self.gridLayout.addWidget(self.label_priority, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit_start.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateTimeEdit_start.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.gridLayout.addWidget(self.dateTimeEdit_start, 1, 1, 1, 1)
        self.label_startdate = QtWidgets.QLabel(self.layoutWidget)
        self.label_startdate.setObjectName("label_startdate")
        self.gridLayout.addWidget(self.label_startdate, 1, 0, 1, 1)
        self.comboBox_priority = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_priority.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_priority.setObjectName("comboBox_priority")
        self.comboBox_priority.addItem("")
        self.comboBox_priority.addItem("")
        self.comboBox_priority.addItem("")
        self.comboBox_priority.addItem("")
        self.gridLayout.addWidget(self.comboBox_priority, 0, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.label_gantt_chart = QtWidgets.QLabel(self.centralwidget)
        self.label_gantt_chart.setGeometry(QtCore.QRect(760, 40, 421, 321))
        self.label_gantt_chart.setText("")
        self.label_gantt_chart.setObjectName("label_gantt_chart")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFocus_Matrix = QtWidgets.QAction(MainWindow)
        self.actionFocus_Matrix.setObjectName("actionFocus_Matrix")
        self.actionOverview = QtWidgets.QAction(MainWindow)
        self.actionOverview.setObjectName("actionOverview")
        self.actionTime_Mgt_Assistant = QtWidgets.QAction(MainWindow)
        self.actionTime_Mgt_Assistant.setObjectName("actionTime_Mgt_Assistant")
        self.menuHelp.addAction(self.actionFocus_Matrix)
        self.menuHelp.addAction(self.actionOverview)
        self.menuHelp.addAction(self.actionTime_Mgt_Assistant)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time Mgt Can be Fun 😄"))
        self.label_overview.setText(_translate("MainWindow", "Overview"))
        self.pushButton_add.setText(_translate("MainWindow", "Add Task"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete Task"))
        self.pushButton_complete.setText(_translate("MainWindow", "Mark as Completed"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Task"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time Used"))
        item = self.tableWidget_1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableWidget_1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Task"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time Used"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Task"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time Used"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Task"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time Used"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End"))
        self.label2.setText(_translate("MainWindow", "2 (Important & Not Urgent)"))
        self.label4.setText(_translate("MainWindow", "4 (Not Important & Not Urgent)"))
        self.label1.setText(_translate("MainWindow", "1 (Important & Urgent)"))
        self.label3.setText(_translate("MainWindow", "3 (Not Important & Urgent)"))
        self.label_enddate.setText(_translate("MainWindow", "End date"))
        self.label_task.setText(_translate("MainWindow", "Task"))
        self.label_priority.setText(_translate("MainWindow", "Priority"))
        self.label_startdate.setText(_translate("MainWindow", "Start date"))
        self.comboBox_priority.setItemText(0, _translate("MainWindow", "1 (Important & Urgent)"))
        self.comboBox_priority.setItemText(1, _translate("MainWindow", "2 (Important & Not Urgent)"))
        self.comboBox_priority.setItemText(2, _translate("MainWindow", "3 (Not Important & Urgent)"))
        self.comboBox_priority.setItemText(3, _translate("MainWindow", "4 (Not Important & Not Urgent)"))
        self.menuHelp.setToolTip(_translate("MainWindow", "See more information"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionFocus_Matrix.setText(_translate("MainWindow", "Focus Matrix"))
        self.actionFocus_Matrix.setToolTip(_translate("MainWindow", "Tips about how to use the focus matrix"))
        self.actionOverview.setText(_translate("MainWindow", "Overview"))
        self.actionOverview.setToolTip(_translate("MainWindow", "Learn more about how to use the gantt chart in the overview section"))
        self.actionTime_Mgt_Assistant.setText(_translate("MainWindow", "Time Mgt Assistant"))
